# Generated by Django 3.2.7 on 2021-09-02 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('link', models.URLField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('follower', models.CharField(blank=True, max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('profile', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('viewCount', models.CharField(max_length=200)),
                ('datePublished', models.CharField(max_length=50)),
                ('likes', models.CharField(default='', max_length=50)),
                ('dislikes', models.CharField(default='', max_length=50)),
                ('comment_num', models.IntegerField(default=0)),
                ('comment_one', models.TextField(default='')),
                ('comment_two', models.TextField(default='')),
                ('comment_three', models.TextField(default='')),
                ('comment_four', models.TextField(default='')),
                ('comment_five', models.TextField(default='')),
                ('authorLink', models.URLField()),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='searchE.author')),
            ],
        ),
    ]
