# Generated by Django 3.2.7 on 2021-09-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile',
            field=models.TextField(blank=True),
        ),
    ]
